# Generated by Django 5.2.1 on 2025-07-15 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_bug_assigned_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
